import { figma } from "@figma/code-connect"

import { ListBox } from "./ListBox.tsx"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  ListBox,
  "https://www.figma.com/design/zSpuR1wOAT99H6YfD29IRl/%F0%9F%90%B8-Hopper-Design-System?node-id=568%3A998",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      size: figma.enum("Size", {
        Small: "sm",
      }),
      // No matching props could be found for these Figma properties:
      // "header": figma.boolean('Header'),
      // "footer": figma.boolean('Footer'),
      // "section2": figma.boolean('Section 2'),
      // "section3": figma.boolean('Section 3')
    },
    example: (props) => <ListBox size={props.size} />,
  },
)
