import { figma } from "@figma/code-connect"

import { ListBoxItem } from "./ListBoxItem.tsx"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  ListBoxItem,
  "https://www.figma.com/design/zSpuR1wOAT99H6YfD29IRl/%F0%9F%90%B8-Hopper-Design-System?node-id=565%3A790",
  {
    props: {
      label: figma.string("Label"),
      upsell: figma.boolean("Upsell"),
      helperContent: figma.string("Helper content"),
      swapIcon: figma.instance("Swap icon"),
      helperText: figma.boolean("Helper text"),
      count: figma.boolean("Count"),
      selected: figma.boolean("Selected"),
      size: figma.enum("Size", {
        Small: "small",
        Medium: "medium",
        Large: "large",
        XSmall: "xsmall",
      }),
      state: figma.enum("State", {
        Default: "default",
        Hover: "hover",
        Press: "press",
        Disabled: "disabled",
        Focus: "focus",
        Loading: "loading",
      }),
      type: figma.enum("Type", {
        Default: "default",
        Icon: "icon",
        Checkbox: "checkbox",
        Radio: "radio",
        Avatar: "avatar",
        Parent: "parent",
        Danger: "danger",
        "Group label": "group-label",
        "Danger + Icon": "danger---icon",
      }),
    },
    example: (props) => <ListBoxItem />,
  },
)
