import { figma } from "@figma/code-connect"

import { Tooltip } from "./Tooltip.tsx"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Tooltip,
  "https://www.figma.com/design/zSpuR1wOAT99H6YfD29IRl/%F0%9F%90%B8-Hopper-Design-System?node-id=665%3A3766",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      top: figma.enum("Type", {
        "User list": "unset",
      }),
      // No matching props could be found for these Figma properties:
      // "content": figma.string('Content')
    },
    example: (props) => <Tooltip top={props.top} />,
  },
)
