import { figma } from "@figma/code-connect"

import { Tab } from "./Tab.tsx"

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  Tab,
  "https://www.figma.com/design/zSpuR1wOAT99H6YfD29IRl/%F0%9F%90%B8-Hopper-Design-System?node-id=671%3A1790",
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "tabGrouping": figma.boolean('Tab grouping'),
      // "layout": figma.enum('Layout', {
      //   "Stand-alone": "stand-alone",
      //   "In card": "in-card",
      //   "Heading": "heading"
      // })
    },
    example: (props) => <Tab />,
  },
)
