import { figma } from "@figma/code-connect"

import { Alert } from "./Alert.tsx"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Alert,
  "https://www.figma.com/design/zSpuR1wOAT99H6YfD29IRl/%F0%9F%90%B8-Hopper-Design-System?node-id=455%3A249",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      isDismissable: figma.boolean("Dismissable"),
      size: figma.enum("Size", {
        Small: "sm",
      }),
      // No matching props could be found for these Figma properties:
      // "content": figma.string('Content'),
      // "title": figma.string('Title'),
      // "dismissable": figma.boolean('Dismissable'),
      // "type": figma.enum('Type', {
      //   "Confirmation": "confirmation",
      //   "Deletion": "deletion"
      // }),
      // "mobile": figma.boolean('Mobile')
    },
    example: (props) => (
      <Alert
        isDismissable={props.isDismissable}
        primaryButtonLabel={/* TODO */}
        size={props.size}
      />
    ),
  },
)
