import { figma } from "@figma/code-connect"
import React from "react"
import { Avatar } from "./Avatar.tsx"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Avatar,
  "https://www.figma.com/design/zSpuR1wOAT99H6YfD29IRl/%F0%9F%90%B8-Hopper-Design-System?node-id=451%3A51",
  {
    props: {
      // No matching props could be found for these Figma properties:
      "name": figma.string('Initials'),
      // "size": figma.enum('Size', {
      //   "XSmall": "xsmall",
      //   "Small": "small",
      //   "Medium": "medium",
      //   "Large": "large",
      //   "XLarge": "xlarge",
      //   "XXLarge": "xxlarge"
      // }),
      // "colour": figma.enum('Colour', {
      //   "Sapphire": "sapphire",
      //   "Quetzal": "quetzal",
      //   "Koi": "koi",
      //   "Moss": "moss",
      //   "Coastal": "coastal",
      //   "Sunken treasure": "sunken-treasure",
      //   "Toad": "toad",
      //   "Amanita": "amanita",
      //   "Rock": "rock"
      // })
    },
    example: (props) => <Avatar name={props.name} />,
  },
)
