import { figma } from "@figma/code-connect"

import { DeletedAvatar } from "./DeletedAvatar.tsx"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  DeletedAvatar,
  "https://www.figma.com/design/zSpuR1wOAT99H6YfD29IRl/%F0%9F%90%B8-Hopper-Design-System?node-id=3332%3A77",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      size: figma.enum("Size", {
        XSmall: "xs",
        Small: "sm",
        XLarge: "2xl",
      }),
    },
    example: (props) => <DeletedAvatar size={props.size} />,
  },
)
