import { figma } from "@figma/code-connect"

import { Popover } from "./Popover.tsx"

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  Popover,
  "https://www.figma.com/design/zSpuR1wOAT99H6YfD29IRl/%F0%9F%90%B8-Hopper-Design-System?node-id=644%3A2467",
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "title": figma.string('Title'),
      // "content": figma.string('Content'),
      // "dismissable": figma.boolean('Dismissable')
    },
    example: (props) => <Popover />,
  },
)
