import { figma } from "@figma/code-connect"

import { Select } from "./Select.tsx"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Select,
  "https://www.figma.com/design/zSpuR1wOAT99H6YfD29IRl/%F0%9F%90%B8-Hopper-Design-System?node-id=669%3A3935",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      size: figma.enum("Size", {
        Small: "sm",
      }),
      // No matching props could be found for these Figma properties:
      // "label": figma.string('Label'),
      // "tooltip": figma.boolean('Tooltip'),
      // "helperContent": figma.string('Helper content'),
      // "helperText": figma.boolean('Helper text'),
      // "errorMessage": figma.string('Error message'),
      // "error": figma.boolean('Error')
    },
    example: (props) => <Select size={props.size} />,
  },
)
