import { figma } from "@figma/code-connect"

import { Disclosure } from "./Disclosure.tsx"

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  Disclosure,
  "https://www.figma.com/design/zSpuR1wOAT99H6YfD29IRl/%F0%9F%90%B8-Hopper-Design-System?node-id=2433%3A3448",
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "label": figma.string('Label'),
      // "descriptionContent": figma.string('Description content'),
      // "description": figma.boolean('Description'),
      // "swapLeadingIcon": figma.instance('Swap leading icon'),
      // "leadingIcon": figma.boolean('Leading icon'),
      // "state": figma.enum('State', {
      //   "Default": "default",
      //   "Hover": "hover",
      //   "Press": "press",
      //   "Focus": "focus"
      // }),
      // "drawer": figma.enum('Drawer', {
      //   "Closed": "closed",
      //   "Opened": "opened"
      // })
    },
    example: (props) => <Disclosure />,
  },
)
