import { figma } from "@figma/code-connect"

import Standalone from "./standalone.tsx"

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  Standalone,
  "https://www.figma.com/design/zSpuR1wOAT99H6YfD29IRl/%F0%9F%90%B8-Hopper-Design-System?node-id=438%3A97",
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "swapLeadingIcon": figma.instance('Swap leading icon'),
      // "swapTrailingIcon": figma.instance('Swap trailing icon'),
      // "leadingIcon": figma.boolean('Leading icon'),
      // "trailingIcon": figma.boolean('Trailing icon'),
      // "label": figma.string('Label'),
      // "type": figma.enum('Type', {
      //   "Primary": "primary",
      //   "Secondary": "secondary"
      // }),
      // "size": figma.enum('Size', {
      //   "Medium": "medium",
      //   "Small": "small"
      // }),
      // "state": figma.enum('State', {
      //   "Default": "default",
      //   "Hover": "hover",
      //   "Press": "press",
      //   "Disabled": "disabled",
      //   "Focus": "focus"
      // })
    },
    example: (props) => <Standalone />,
  },
)
