import { figma } from "@figma/code-connect"

import { Callout } from "./Callout.tsx"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Callout,
  "https://www.figma.com/design/zSpuR1wOAT99H6YfD29IRl/%F0%9F%90%B8-Hopper-Design-System?node-id=522%3A286",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      top: figma.enum("Type", {
        Upsell: "unset",
      }),
      // No matching props could be found for these Figma properties:
      // "button": figma.boolean('Button'),
      // "dismissible": figma.boolean('Dismissible'),
      // "title": figma.string('Title'),
      // "content": figma.string('Content'),
      // "icon": figma.boolean('Icon')
    },
    example: (props) => <Callout top={props.top} />,
  },
)
