import packageJson from "../../package.json" with { type: "json" };

const TokensVersion = packageJson.version;

export const HOPPER_PREFIX = "hop";
export const StyledSystemRootCssClass = `${HOPPER_PREFIX}-${TokensVersion.replaceAll(".", "-")}`;
export const AUTO_GENERATED_COMMENT = "This file is generated by Style Dictionary. Do not edit directly.";

export const BUILD_PATH = "dist/";
export const STORYBOOK_BUILD_PATH = "../src/stories";
export const DOCS_BUILD_PATH = "../../../apps/docs";
export const STYLED_SYSTEM_BUILD_PATH = "../styled-system/src/tokens/generated/";
export const STYLED_SYSTEM_THEME_BUILD_PATH = "../styled-system/src/theme/";

export const THEME_SRC_PATH = "src/tokens/semantic/";
