import { figma } from "@figma/code-connect"

import { Badge } from "./Badge.tsx"

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  Badge,
  "https://www.figma.com/design/zSpuR1wOAT99H6YfD29IRl/%F0%9F%90%B8-Hopper-Design-System?node-id=458%3A200",
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "count": figma.string('Count'),
      // "type": figma.enum('Type', {
      //   "Primary": "primary",
      //   "Secondary": "secondary",
      //   "Subdued": "subdued"
      // }),
      // "state": figma.enum('State', {
      //   "Default": "default",
      //   "Hover": "hover",
      //   "Press": "press",
      //   "Selected": "selected",
      //   "Disabled": "disabled"
      // })
    },
    example: (props) => <Badge />,
  },
)
