import { figma } from "@figma/code-connect"

import { Checkbox } from "./Checkbox.tsx"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Checkbox,
  "https://www.figma.com/design/zSpuR1wOAT99H6YfD29IRl/%F0%9F%90%B8-Hopper-Design-System?node-id=536%3A396",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      size: figma.enum("Size", {
        Small: "sm",
      }),
      isIndeterminate: figma.enum("Checkbox", {
        Indeterminate: true,
      }),
      // No matching props could be found for these Figma properties:
      // "label": figma.string('Label'),
      // "helperContent": figma.string('Helper content'),
      // "helperText": figma.boolean('Helper text'),
      // "tooltip": figma.boolean('Tooltip'),
      // "state": figma.enum('State', {
      //   "Default": "default",
      //   "Hover": "hover",
      //   "Press": "press",
      //   "Disabled": "disabled",
      //   "Focus": "focus",
      //   "Error": "error"
      // })
    },
    example: (props) => (
      <Checkbox size={props.size} isIndeterminate={props.isIndeterminate} />
    ),
  },
)
