import { figma } from "@figma/code-connect"
import { Footer } from "./Footer.tsx"

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  Footer,
  "https://www.figma.com/design/zSpuR1wOAT99H6YfD29IRl/%F0%9F%90%B8-Hopper-Design-System?node-id=867%3A4661",
  {
    props: {
        children: figma.children('*')
    },
    example: (props) => <Footer >{props.children}</Footer>,
  },
)

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  Footer,
  "https://www.figma.com/design/zSpuR1wOAT99H6YfD29IRl/%F0%9F%90%B8-Hopper-Design-System?node-id=640%3A2669",
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "backButton": figma.boolean('Back button'),
      // "type": figma.enum('Type', {
      //   "Button group": "button-group",
      //   "Stepper": "stepper",
      //   "Bottom navigation": "bottom-navigation"
      // }),
      // "mobile": figma.boolean('Mobile'),
      // "layout": figma.enum('Layout', {
      //   "Default": "default",
      //   "Full-screen": "full-screen"
      // })
      children: figma.children('*')
    },
    example: (props) => <Footer >{props.children}</Footer>,
  },
)
