import { figma } from "@figma/code-connect"

import { Tile } from "./Tile.tsx"

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  Tile,
  "https://www.figma.com/design/zSpuR1wOAT99H6YfD29IRl/%F0%9F%90%B8-Hopper-Design-System?node-id=1516%3A9068",
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "listNumber": figma.string('List number'),
      // "orderedListItem": figma.boolean('Ordered list item'),
      // "descriptionContent": figma.string('Description content'),
      // "description": figma.boolean('Description'),
      // "swapIcon": figma.instance('Swap icon'),
      // "leadingIcon": figma.boolean('Leading icon'),
      // "swapLargeIcon": figma.instance('Swap large icon'),
      // "label": figma.string('Label'),
      // "largeLeadingIcon": figma.boolean('Large leading icon'),
      // "state": figma.enum('State', {
      //   "Default": "default",
      //   "Hover": "hover",
      //   "Press": "press",
      //   "Active": "active",
      //   "Disabled": "disabled",
      //   "Focus": "focus",
      //   "Active-disabled": "active-disabled"
      // })
    },
    example: (props) => <Tile id={/* TODO */} />,
  },
)
