import { figma } from "@figma/code-connect"

import { Tag } from "./Tag.tsx"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Tag,
  "https://www.figma.com/design/zSpuR1wOAT99H6YfD29IRl/%F0%9F%90%B8-Hopper-Design-System?node-id=672%3A2374",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      isLoading: figma.boolean("Leading icon"),
      size: figma.enum("Size", {
        Small: "sm",
      }),
      isDisabled: figma.boolean("Dismissable"),
      rel: figma.string("Label"),
      top: figma.enum("Type", {
        Caution: "auto",
      }),
      // No matching props could be found for these Figma properties:
      // "label": figma.string('Label'),
      // "swapLeadingIcon": figma.instance('Swap leading icon'),
      // "leadingIcon": figma.boolean('Leading icon'),
      // "dismissable": figma.boolean('Dismissable')
    },
    example: (props) => (
      <Tag
        isLoading={props.isLoading}
        size={props.size}
        isDisabled={props.isDisabled}
        rel={props.rel}
        top={props.top}
      />
    ),
  },
)
