import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

// Get the directory name in ES modules
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

/**
 * Interface for metadata object structure
 */
interface IconMetadata {
    name: string;
    description: string;
    keywords: string[];
}

/**
 * Interface for the merged metadata object that includes a comment field
 */
interface MergedMetadata {
    "//comment": string;
    [key: string]: IconMetadata | string;
}

/**
 * Merges all JSON files in a specified directory into a single output file
 * @param {string} sourceDir - The directory containing the JSON files to merge
 * @param {string} outputFilePath - The path where the merged JSON will be written
 * @param {string} type - The type of icons being processed (for logging)
 * @returns {Promise<MergedMetadata>} - The merged data object
 */
async function mergeMetadataFiles(
    sourceDir: string,
    outputFilePath: string,
    type: string
): Promise<MergedMetadata> {
    try {
        // Get all JSON files in the directory
        const files = fs.readdirSync(sourceDir).filter(file => file.endsWith(".json"));

        console.log(`Found ${files.length} ${type} JSON files to merge`);

        // Create an object to store the merged data with a comment field
        const mergedData: MergedMetadata = {
            "//comment": "This file is generated by the mergeAllMetadataFiles script. Do not edit directly."
        };

        // Process each file
        for (const file of files) {
            try {
                // Read the file content
                const filePath = path.join(sourceDir, file);
                const fileContent = fs.readFileSync(filePath, "utf8");

                // Parse the JSON content
                const jsonData = JSON.parse(fileContent) as IconMetadata;

                // Use the filename (without extension) as the key
                const key = path.basename(file, ".json");

                // Add the data to the merged object
                mergedData[key] = jsonData;
            } catch (fileError) {
                console.error(`Error processing ${type} file ${file}:`, fileError);
            }
        }

        // Write the merged data to the output file
        fs.writeFileSync(outputFilePath, JSON.stringify(mergedData, null, 2), "utf8");

        console.log(`Successfully merged ${Object.keys(mergedData).length - 1} ${type} files into ${outputFilePath}`);

        return mergedData;
    } catch (error) {
        console.error(`Error merging ${type} metadata files:`, error);
        throw error;
    }
}

// Define paths for regular icons
const regularIconsMetadataDir = path.join(__dirname, "../src/icons/metadata");
const regularIconsOutputFile = path.join(__dirname, "../src/icons/merged-metadata.json");

// Define paths for rich icons
const richIconsMetadataDir = path.join(__dirname, "../src/rich-icons/metadata");
const richIconsOutputFile = path.join(__dirname, "../src/rich-icons/merged-metadata.json");

/**
 * Merges metadata for both regular and rich icons
 */
async function mergeAllMetadata(): Promise<void> {
    try {
        // Merge regular icons metadata
        await mergeMetadataFiles(regularIconsMetadataDir, regularIconsOutputFile, "regular icon");

        // Merge rich icons metadata
        await mergeMetadataFiles(richIconsMetadataDir, richIconsOutputFile, "rich icon");

        console.log("All metadata merging completed successfully");
    } catch (err) {
        console.error("Metadata merging failed:", err);
    }
}

// Run the merged process
mergeAllMetadata();
