import { figma } from "@figma/code-connect"

import { Radio } from "./Radio.tsx"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Radio,
  "https://www.figma.com/design/zSpuR1wOAT99H6YfD29IRl/%F0%9F%90%B8-Hopper-Design-System?node-id=549%3A630",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      size: figma.enum("Size", {
        Small: "sm",
      }),
      // No matching props could be found for these Figma properties:
      // "helperContent": figma.string('Helper content'),
      // "helperText": figma.boolean('Helper text'),
      // "label": figma.string('Label'),
      // "tooltip": figma.boolean('Tooltip'),
      // "state": figma.enum('State', {
      //   "Default": "default",
      //   "Hover": "hover",
      //   "Focus": "focus",
      //   "Disabled": "disabled",
      //   "Error": "error",
      //   "Press": "press"
      // }),
      // "selected": figma.boolean('Selected')
    },
    example: (props) => <Radio size={props.size} value={/* TODO */} />,
  },
)
