import { figma } from "@figma/code-connect"
import { TDProps, TFoot, TH, THProps } from "@hopper-ui/styled-system"

import { Table, TD } from "@hopper-ui/styled-system"

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  Table,
  "https://www.figma.com/design/zSpuR1wOAT99H6YfD29IRl/%F0%9F%90%B8-Hopper-Design-System?node-id=685%3A3145",
  {
    props: {
        children: figma.children('*')
    },
    example: (props) => <Table>{props.children}</Table>,
  },
)

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect<TDProps>(
  TD,
  "https://www.figma.com/design/zSpuR1wOAT99H6YfD29IRl/%F0%9F%90%B8-Hopper-Design-System?node-id=685%3A1948",
  {
    props: {
        children: figma.children('*')
    },
    example: (props) => <TD>{props.children}</TD>,
  },
)

figma.connect<THProps>(
  TH,
  "https://www.figma.com/design/zSpuR1wOAT99H6YfD29IRl/%F0%9F%90%B8-Hopper-Design-System?node-id=685%3A1948",
  {
    props: {
        children: figma.children('*')
    },
    example: (props) => <TH>{props.children}</TH>,
  },
)





figma.connect(
  TD,
  "https://www.figma.com/design/zSpuR1wOAT99H6YfD29IRl/%F0%9F%90%B8-Hopper-Design-System?node-id=681%3A2138",
  {
    props: {
        children: figma.children('*')
    },
    example: (props) => <TD>{props.children}</TD>,
  },
)


figma.connect(
  TD,
  "https://www.figma.com/design/zSpuR1wOAT99H6YfD29IRl/%F0%9F%90%B8-Hopper-Design-System?node-id=681%3A2170",
  {
    props: {
        children: figma.children('*')
    },
    example: (props) => <TD>{props.children}</TD>,
  },
)

figma.connect(
  TD,
  "https://www.figma.com/design/zSpuR1wOAT99H6YfD29IRl/%F0%9F%90%B8-Hopper-Design-System?node-id=681%3A2130",
  {
    props: {
        children: figma.children('*')
    },
    example: (props) => <TD>{props.children}</TD>,
  },
)



figma.connect(
  TFoot,
  "https://www.figma.com/design/zSpuR1wOAT99H6YfD29IRl/%F0%9F%90%B8-Hopper-Design-System?node-id=6281%3A4733",
  {
    props: {

    },
    example: (props) => <TFoot />,
  },
)
