name: Settings
description: >-
  Used to represent configuration options, preferences, or system controls.
  Often depicted as a gear or cog, this icon is commonly used in interfaces
  to indicate areas where users can customize, configure, or adjust application
  behavior and appearance.
keywords:
  - settings
  - configuration
  - preferences
  - options
  - controls
  - customization
  - setup
  - adjustment
  - parameters
  - gear
  - system settings
  - preferences menu
