import { figma } from "@figma/code-connect"
import { Card, CardProps } from "./Card.tsx"

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect<CardProps>(
  Card,
  "https://www.figma.com/design/zSpuR1wOAT99H6YfD29IRl/%F0%9F%90%B8-Hopper-Design-System?node-id=436%3A254",
  {
    props: {
        children: figma.children('*')
    },
    example: (props) => <Card>{props.children}</Card>,
  },
)
