import { figma } from "@figma/code-connect"

import { ProfileIcon } from "./ProfileIcon.tsx"

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  ProfileIcon,
  "https://www.figma.com/design/zSpuR1wOAT99H6YfD29IRl/%F0%9F%90%B8-Hopper-Design-System?node-id=725%3A4418",
  {
    props: {},
    example: (props) => <ProfileIcon />,
  },
)
