import { defineHopperRslibBuildConfig } from "@hopper-ui/rslib-config";

import packageJson from "./package.json" with { type: "json" };

export default defineHopperRslibBuildConfig({
    version: packageJson.version,
    aggregateCss: true,
    // The theme stylesheets are generated by @hopper-ui/tokens and copied verbatim by the build
    // script, not produced by the bundler. Keeping them out of the entry set leaves them
    // byte-identical, which matters because every Chromatic story renders through them.
    ignore: ["./src/theme/generated/**"]
});
