import { figma } from "@figma/code-connect"

import { Input } from "./Input.tsx"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Input,
  "https://www.figma.com/design/zSpuR1wOAT99H6YfD29IRl/%F0%9F%90%B8-Hopper-Design-System?node-id=588%3A864",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      size: figma.enum("Size", {
        Small: "sm",
      }),
      disabled: figma.enum("State", {
        Disabled: true,
      }),
      placeholder: figma.string("Placeholder text"),
      // No matching props could be found for these Figma properties:
      // "prefix": figma.boolean('Prefix'),
      // "suffixGroup": figma.boolean('Suffix group'),
      // "limitNumber": figma.string('Limit number'),
      // "characterLimit": figma.boolean('Character limit'),
      // "clear": figma.boolean('Clear'),
      // "suffix": figma.boolean('Suffix'),
      // "placeholderText": figma.string('Placeholder text'),
      // "textField": figma.string('Text field'),
      // "stepper": figma.boolean('Stepper'),
      // "content": figma.enum('Content', {
      //   "Empty": "empty",
      //   "Placeholder": "placeholder",
      //   "Filled": "filled",
      //   "Tag": "tag"
      // })
    },
    example: (props) => (
      <Input
        size={props.size}
        disabled={props.disabled}
        placeholder={props.placeholder}
      />
    ),
  },
)
