import { figma } from "@figma/code-connect"

import { TextField } from "./TextField.tsx"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  TextField,
  "https://www.figma.com/design/zSpuR1wOAT99H6YfD29IRl/%F0%9F%90%B8-Hopper-Design-System?node-id=605%3A3782",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      "aria-errormessage": figma.string("Error message"),
      size: figma.enum("Size", {
        Small: "sm",
      }),
      // No matching props could be found for these Figma properties:
      // "tooltip": figma.boolean('Tooltip'),
      // "helperContent": figma.string('Helper content'),
      // "helperText": figma.boolean('Helper text'),
      // "errorMessage": figma.string('Error message'),
      // "label": figma.string('Label'),
      // "error": figma.boolean('Error')
    },
    example: (props) => (
      <TextField
        aria-errormessage={props["aria-errormessage"]}
        size={props.size}
      />
    ),
  },
)
